server:
  port: 8807
  servlet:
    context-path: /activemq/publisher
spring:
  application:
    name: ActiveMqPublisher # 服务名称
  activemq:
    broker-url: tcp://${ip}:61616
    user: root
    password: 2762581@com