server:
  port: 8808
  servlet:
    context-path: /kafka/consumer
spring:
  kafka:
    bootstrap-servers: 124.221.27.253:9092
  application:
    name: KafkaConsumer # 服务名称
  cloud:
    stream:
      kafka:
        binder:
          auto-create-topics: true   # 自动创建topics
          brokers: 124.221.27.253:9092 # kafka地址
          health-timeout: 15 # 等待获取分区信息的时间，以秒为单位。如果这个计时器过期，健康报告就会关闭
      bindings:
        # 格式:<functionName>-<in/out>-<index>
        # 其中functionName为声明的Consumer的BeanName
        SuperStarConsumer-in-0:
          destination: SuperStarTopic # topic
